#!/bin/sh
$HOME/.fehbg &
$HOME/.icewm/combo mkmenu &
xrandr --output DisplayPort-0 --mode 1920x1080 --rate 144
xrandr --output HDMI-A-0 --mode 1920x1080 --rate 75
pasystray &
dolphin &
gentoo-pipewire-launcher &

